unique_ids:
  assets:
    standard-page.html: CWJFSHS7P5BTXJQIHE27KNHS5ALOX4A4
    theme.css: GEQF4E3DI6EVPCARI7QLPUTURVN7BPZN
  forms:
    Form1: VZT4XGED6EXZYCVCM64LMQCOLFAWRUNX
  modules: {}
  scripts: {}
  server_modules: {}
